@startuml
class Account {
'    - _balance : Denomination
    + Account()
    + Deposit(denomination:Denomination) : void
    + ExchangeTo(currency:Currency) : void
    + Balance() : Denomination
}

Account *-- "1" Denomination 
@enduml
