@startuml
class CurrencyDatabase {
'    - {static} _currencyDictionary : Dictionary<string, Currency>
    - {static} Local : CurrencyDatabase <<get>>
    {static} Database()
    - Database()
    - {static} <<readonly>> Instance : Database
    + {static} Update() : void
    + GetCurrency(currencyCode:string) : Currency
    + GetCurrencies() : List<Currency>
}

CurrencyDatabase "1" o-- "many" Currency 
CurrencyDatabase ..> XmlTools : call
@enduml
