@startuml
interface "IFlyweight"<T> {
    + GetState() : T
}
class "Flyweight"<T> {
    + State : T
    + Flyweight(state:T)
    + GetState() : T
    + <<override>> ToString() : string
}
"IFlyweight" "<T>" <|-L- "Flyweight"
@enduml
