@startuml
interface "ISubject"<T> {
    + Operation(subject:T) : T
}
class CorrectedFlyweightFactory {
    - _flyweightFactory : FlyweightFactory<string>
    + CorrectedFlyweightFactory(flyweightFactory:FlyweightFactory<string>)
    + Operation(subject:string) : Flyweight<string>
}
@enduml
