@startuml

package Iterator{
class ClosestFireTrucksIterator {
    - _fireTrucks : List<FireTruck>
    - _targetLocation : Vector2
    - _controlStation : List<ISubject>
    
    - RefreshIterator()
    + hasNext() : bool
    + getNext() : FireTruck
}
"IIterator`1" "<FireTruck>" <|-- ClosestFireTrucksIterator

}
@enduml
