@startuml

package Observer{
    class ControlStation {
        - <<readonly>> _observators : List<IObserver>
        - <<readonly>> _incidents : List<Incident>
        + ControlStation()
        + RegisterIncident(incident:Incident) : void
        + RegisterFireStations(fireStations:List<FireStation>) : void
    }
}

ControlStation --> ISubject
@enduml
