@startuml
interface IExecutionStrategy {
    execute() : float
}
class Emergency {
    + execute() : float
}
class Fake {
    + execute() : float
}
IExecutionStrategy <|-- Emergency
IExecutionStrategy <|-- Fake
@enduml
