@startuml

package Observer{
    class FireStation {
        + Name : string <<get>>
        + FireStation(name:string, position:Vector2)
        + <<override>> ToString() : string
    }
}

FireStation --> IObserver
@enduml
